# Generated by Django 4.0.5 on 2022-06-20 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Neighbourhood Title')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Neighbourhood Location')),
                ('county', models.CharField(blank=True, max_length=150, null=True, verbose_name='Neighbourhood County')),
                ('neighbourhood_image', models.ImageField(upload_to='Media')),
                ('health_department', models.CharField(max_length=100, verbose_name='Health')),
                ('police_department', models.CharField(max_length=100, verbose_name='Police')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('neighbourhood_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media')),
                ('Bio', models.TextField(blank=True, max_length=300, null=True)),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ujamaa.neighbourhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('business_email', models.EmailField(blank=True, max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('Owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ujamaa.profile')),
            ],
        ),
    ]
