# Generated by Django 4.0.5 on 2022-06-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujamaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
