# Generated by Django 4.0.5 on 2022-06-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujamaa', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
