# Generated by Django 4.0.5 on 2022-06-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ujamaa', '0004_alter_neighbourhood_neighbourhood_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujamaa.profile'),
        ),
    ]
